import { PageIntro } from "./PageIntro";

export function RuleAlertPanel() {
  return (
    <PageIntro
      eyebrow="Discipline"
      title="Rule Alerts"
      description="See blockers, warnings, and reminders generated by the YAML rule engine."
      nextStage="Alerts will become part of the trade checklist workflow in Stage 5."
    />
  );
}
